#!/usr/bin/env python3
"""Compile the smoke test's Cg shaders and emit them as a committed header.

The header is checked in, so only regenerating it needs psp2cgc.

  python embed_shaders.py --cgc "<path>/psp2cgc.exe"
"""

import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SHADER_DIR = os.path.join(HERE, "..", "..", "src", "vita", "test", "shaders")
OUT_HEADER = os.path.join(SHADER_DIR, "smoke_shaders.h")

SHADERS = {"smoke_v": "sce_vp_psp2", "smoke_f": "sce_fp_psp2"}
CGC_FLAGS = ["-O3", "-fastmath"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cgc", required=True)
    args = ap.parse_args()

    blobs = {}
    for name, profile in sorted(SHADERS.items()):
        source = os.path.join(SHADER_DIR, name + ".cg")
        output = os.path.join(SHADER_DIR, name + ".gxp")
        result = subprocess.run([args.cgc, "-profile", profile, source, "-o", output] + CGC_FLAGS,
                                capture_output=True, text=True)
        if result.returncode != 0 or not os.path.exists(output):
            sys.exit("%s failed to compile:\n%s%s" % (name, result.stdout, result.stderr))

        with open(output, "rb") as f:
            blob = f.read()
        os.remove(output)
        if blob[:4] != b"GXP\0":
            sys.exit("%s is not a GXP blob" % name)
        blobs[name] = blob

    lines = ["// Generated by scripts/vita/embed_shaders.py -- do not edit.", "",
             "#pragma once", ""]
    for name, blob in sorted(blobs.items()):
        lines.append("static const unsigned char %s_gxp[] = {" % name)
        for i in range(0, len(blob), 12):
            lines.append("\t" + ", ".join("0x%02x" % b for b in blob[i:i + 12]) + ",")
        lines.append("};")
        lines.append("")

    with open(OUT_HEADER, "w", newline="\n") as f:
        f.write("\n".join(lines))

    print("wrote %s (%s)" % (os.path.relpath(OUT_HEADER),
                             ", ".join("%s %d bytes" % (n, len(b)) for n, b in sorted(blobs.items()))))


if __name__ == "__main__":
    main()
