// D3D9 declarations the engine's headers need, for targets without the SDK.
// Generated by scripts/vita/gen_d3d9_shim.py -- do not edit.
#pragma once

#include <stdint.h>

#include <qcommon/sys_types.h>

typedef int32_t HRESULT;
typedef uint32_t D3DCOLOR;

#define D3D_OK 0
#define MAX_DEVICE_IDENTIFIER_STRING 512

typedef struct _GUID
{
    uint32_t Data1;
    uint16_t Data2;
    uint16_t Data3;
    unsigned char Data4[8];
} GUID;

struct IDirect3D9;
struct IDirect3DDevice9;
struct IDirect3DBaseTexture9;
struct IDirect3DTexture9;
struct IDirect3DVolumeTexture9;
struct IDirect3DCubeTexture9;
struct IDirect3DVertexBuffer9;
struct IDirect3DIndexBuffer9;
struct IDirect3DVertexShader9;
struct IDirect3DPixelShader9;
struct IDirect3DVertexDeclaration9;
struct IDirect3DSurface9;
struct IDirect3DQuery9;
struct IDirect3DSwapChain9;

enum _D3DBACKBUFFER_TYPE
{
    D3DBACKBUFFER_TYPE_MONO            = 0,
};
typedef enum _D3DBACKBUFFER_TYPE D3DBACKBUFFER_TYPE;

enum _D3DBLEND
{
};
typedef enum _D3DBLEND D3DBLEND;

enum _D3DBLENDOP
{
};
typedef enum _D3DBLENDOP D3DBLENDOP;

enum _D3DCUBEMAP_FACES
{
    D3DCUBEMAP_FACE_POSITIVE_X         = 0,
    D3DCUBEMAP_FACE_NEGATIVE_X         = 1,
    D3DCUBEMAP_FACE_POSITIVE_Y         = 2,
    D3DCUBEMAP_FACE_NEGATIVE_Y         = 3,
    D3DCUBEMAP_FACE_POSITIVE_Z         = 4,
    D3DCUBEMAP_FACE_NEGATIVE_Z         = 5,
};
typedef enum _D3DCUBEMAP_FACES D3DCUBEMAP_FACES;

enum _D3DDECLTYPE
{
};
typedef enum _D3DDECLTYPE D3DDECLTYPE;

enum _D3DDECLUSAGE
{
};
typedef enum _D3DDECLUSAGE D3DDECLUSAGE;

enum _D3DDEVTYPE
{
    D3DDEVTYPE_HAL                     = 1,
};
typedef enum _D3DDEVTYPE D3DDEVTYPE;

enum _D3DFILLMODE
{
    D3DFILL_WIREFRAME                  = 2,
    D3DFILL_SOLID                      = 3,
};
typedef enum _D3DFILLMODE D3DFILLMODE;

enum _D3DFORMAT
{
    D3DFMT_UNKNOWN                     = 0,
    D3DFMT_A8R8G8B8                    = 21,
    D3DFMT_X8R8G8B8                    = 22,
    D3DFMT_R5G6B5                      = 23,
    D3DFMT_A1R5G5B5                    = 25,
    D3DFMT_A8                          = 28,
    D3DFMT_A8B8G8R8                    = 32,
    D3DFMT_L8                          = 50,
    D3DFMT_A8L8                        = 51,
    D3DFMT_D16_LOCKABLE                = 70,
    D3DFMT_D15S1                       = 73,
    D3DFMT_D24S8                       = 75,
    D3DFMT_D24X8                       = 77,
    D3DFMT_D16                         = 80,
    D3DFMT_D24FS8                      = 83,
    D3DFMT_INDEX16                     = 101,
    D3DFMT_G16R16F                     = 112,
    D3DFMT_R32F                        = 114,
    D3DFMT_DXT1                        = 0x31545844,
    D3DFMT_DXT3                        = 0x33545844,
    D3DFMT_DXT5                        = 0x35545844,
};
typedef enum _D3DFORMAT D3DFORMAT;

enum _D3DMULTISAMPLE_TYPE
{
    D3DMULTISAMPLE_NONE                = 0,
    D3DMULTISAMPLE_NONMASKABLE         = 1,
};
typedef enum _D3DMULTISAMPLE_TYPE D3DMULTISAMPLE_TYPE;

enum _D3DPOOL
{
    D3DPOOL_DEFAULT                    = 0,
    D3DPOOL_MANAGED                    = 1,
    D3DPOOL_SYSTEMMEM                  = 2,
    D3DPOOL_SCRATCH                    = 3,
};
typedef enum _D3DPOOL D3DPOOL;

enum _D3DPRIMITIVETYPE
{
    D3DPT_TRIANGLELIST                 = 4,
};
typedef enum _D3DPRIMITIVETYPE D3DPRIMITIVETYPE;

enum _D3DQUERYTYPE
{
    D3DQUERYTYPE_EVENT                 = 8,
    D3DQUERYTYPE_OCCLUSION             = 9,
};
typedef enum _D3DQUERYTYPE D3DQUERYTYPE;

enum _D3DRENDERSTATETYPE
{
    D3DRS_ZENABLE                      = 7,
    D3DRS_FILLMODE                     = 8,
    D3DRS_ZWRITEENABLE                 = 14,
    D3DRS_ALPHATESTENABLE              = 15,
    D3DRS_SRCBLEND                     = 19,
    D3DRS_DESTBLEND                    = 20,
    D3DRS_CULLMODE                     = 22,
    D3DRS_ZFUNC                        = 23,
    D3DRS_ALPHAREF                     = 24,
    D3DRS_ALPHAFUNC                    = 25,
    D3DRS_ALPHABLENDENABLE             = 27,
    D3DRS_STENCILENABLE                = 52,
    D3DRS_STENCILFAIL                  = 53,
    D3DRS_STENCILZFAIL                 = 54,
    D3DRS_STENCILPASS                  = 55,
    D3DRS_STENCILFUNC                  = 56,
    D3DRS_COLORWRITEENABLE             = 168,
    D3DRS_BLENDOP                      = 171,
    D3DRS_SCISSORTESTENABLE            = 174,
    D3DRS_SLOPESCALEDEPTHBIAS          = 175,
    D3DRS_ADAPTIVETESS_Y               = 181,
    D3DRS_TWOSIDEDSTENCILMODE          = 185,
    D3DRS_CCW_STENCILFAIL              = 186,
    D3DRS_CCW_STENCILZFAIL             = 187,
    D3DRS_CCW_STENCILPASS              = 188,
    D3DRS_CCW_STENCILFUNC              = 189,
    D3DRS_DEPTHBIAS                    = 195,
    D3DRS_SEPARATEALPHABLENDENABLE     = 206,
    D3DRS_SRCBLENDALPHA                = 207,
    D3DRS_DESTBLENDALPHA               = 208,
    D3DRS_BLENDOPALPHA                 = 209,
};
typedef enum _D3DRENDERSTATETYPE D3DRENDERSTATETYPE;

enum _D3DRESOURCETYPE
{
    D3DRTYPE_SURFACE                   = 1,
    D3DRTYPE_TEXTURE                   = 3,
};
typedef enum _D3DRESOURCETYPE D3DRESOURCETYPE;

enum _D3DSAMPLERSTATETYPE
{
    D3DSAMP_ADDRESSU                   = 1,
    D3DSAMP_ADDRESSV                   = 2,
    D3DSAMP_ADDRESSW                   = 3,
    D3DSAMP_MAGFILTER                  = 5,
    D3DSAMP_MINFILTER                  = 6,
    D3DSAMP_MIPFILTER                  = 7,
    D3DSAMP_MIPMAPLODBIAS              = 8,
    D3DSAMP_MAXANISOTROPY              = 10,
};
typedef enum _D3DSAMPLERSTATETYPE D3DSAMPLERSTATETYPE;

enum _D3DSHADER_INSTRUCTION_OPCODE_TYPE
{
    D3DSIO_DEFB                        = 47,
    D3DSIO_DEFI                        = 48,
    D3DSIO_DEF                         = 81,
};
typedef enum _D3DSHADER_INSTRUCTION_OPCODE_TYPE D3DSHADER_INSTRUCTION_OPCODE_TYPE;

enum _D3DSTENCILOP
{
};
typedef enum _D3DSTENCILOP D3DSTENCILOP;

enum _D3DSWAPEFFECT
{
    D3DSWAPEFFECT_DISCARD              = 1,
};
typedef enum _D3DSWAPEFFECT D3DSWAPEFFECT;

enum _D3DTEXTUREFILTERTYPE
{
    D3DTEXF_NONE                       = 0,
    D3DTEXF_POINT                      = 1,
    D3DTEXF_LINEAR                     = 2,
};
typedef enum _D3DTEXTUREFILTERTYPE D3DTEXTUREFILTERTYPE;

enum _D3DZBUFFERTYPE
{
    D3DZB_FALSE                        = 0,
    D3DZB_TRUE                         = 1,
};
typedef enum _D3DZBUFFERTYPE D3DZBUFFERTYPE;

struct _D3DADAPTER_IDENTIFIER9
{
    char            Driver[MAX_DEVICE_IDENTIFIER_STRING];
    char            Description[MAX_DEVICE_IDENTIFIER_STRING];
    char            DeviceName[32];
    #ifdef _WIN32
    LARGE_INTEGER   DriverVersion;
    #else
    DWORD           DriverVersionLowPart;
    DWORD           DriverVersionHighPart;
    #endif
    DWORD           VendorId;
    DWORD           DeviceId;
    DWORD           SubSysId;
    DWORD           Revision;
    GUID            DeviceIdentifier;
    DWORD           WHQLLevel;
};
typedef struct _D3DADAPTER_IDENTIFIER9 D3DADAPTER_IDENTIFIER9;

struct _D3DBOX
{
    UINT                Left;
    UINT                Top;
    UINT                Right;
    UINT                Bottom;
    UINT                Front;
    UINT                Back;
};
typedef struct _D3DBOX D3DBOX;

struct _D3DDISPLAYMODE
{
    UINT            Width;
    UINT            Height;
    UINT            RefreshRate;
    D3DFORMAT       Format;
};
typedef struct _D3DDISPLAYMODE D3DDISPLAYMODE;

struct _D3DGAMMARAMP
{
    WORD                red  [256];
    WORD                green[256];
    WORD                blue [256];
};
typedef struct _D3DGAMMARAMP D3DGAMMARAMP;

struct _D3DLOCKED_BOX
{
    INT                 RowPitch;
    INT                 SlicePitch;
    void*               pBits;
};
typedef struct _D3DLOCKED_BOX D3DLOCKED_BOX;

struct _D3DLOCKED_RECT
{
    INT                 Pitch;
    void*               pBits;
};
typedef struct _D3DLOCKED_RECT D3DLOCKED_RECT;

struct _D3DPRESENT_PARAMETERS_
{
    UINT                BackBufferWidth;
    UINT                BackBufferHeight;
    D3DFORMAT           BackBufferFormat;
    UINT                BackBufferCount;
    D3DMULTISAMPLE_TYPE MultiSampleType;
    DWORD               MultiSampleQuality;
    D3DSWAPEFFECT       SwapEffect;
    HWND                hDeviceWindow;
    BOOL                Windowed;
    BOOL                EnableAutoDepthStencil;
    D3DFORMAT           AutoDepthStencilFormat;
    DWORD               Flags;
    UINT                FullScreen_RefreshRateInHz;
    UINT                PresentationInterval;
};
typedef struct _D3DPRESENT_PARAMETERS_ D3DPRESENT_PARAMETERS;

struct _D3DPSHADERCAPS2_0
{
    DWORD Caps;
    INT DynamicFlowControlDepth;
    INT NumTemps;
    INT StaticFlowControlDepth;
    INT NumInstructionSlots;
};
typedef struct _D3DPSHADERCAPS2_0 D3DPSHADERCAPS2_0;

struct _D3DSURFACE_DESC
{
    D3DFORMAT           Format;
    D3DRESOURCETYPE     Type;
    DWORD               Usage;
    D3DPOOL             Pool;
    D3DMULTISAMPLE_TYPE MultiSampleType;
    DWORD               MultiSampleQuality;
    UINT                Width;
    UINT                Height;
};
typedef struct _D3DSURFACE_DESC D3DSURFACE_DESC;

struct _D3DVERTEXELEMENT9
{
    WORD    Stream;     // Stream index
    WORD    Offset;     // Offset in the stream in bytes
    BYTE    Type;       // Data type
    BYTE    Method;     // Processing method
    BYTE    Usage;      // Semantics
    BYTE    UsageIndex; // Semantic index
};
typedef struct _D3DVERTEXELEMENT9 D3DVERTEXELEMENT9;
typedef struct _D3DVERTEXELEMENT9 LPD3DVERTEXELEMENT9;

struct _D3DVIEWPORT9
{
    DWORD       X;
    DWORD       Y;
    DWORD       Width;
    DWORD       Height;
    float       MinZ;
    float       MaxZ;
};
typedef struct _D3DVIEWPORT9 D3DVIEWPORT9;

struct _D3DVOLUME_DESC
{
    D3DFORMAT           Format;
    D3DRESOURCETYPE     Type;
    DWORD               Usage;
    D3DPOOL             Pool;
    UINT                Width;
    UINT                Height;
    UINT                Depth;
};
typedef struct _D3DVOLUME_DESC D3DVOLUME_DESC;

struct _D3DVSHADERCAPS2_0
{
    DWORD Caps;
    INT DynamicFlowControlDepth;
    INT NumTemps;
    INT StaticFlowControlDepth;
};
typedef struct _D3DVSHADERCAPS2_0 D3DVSHADERCAPS2_0;

struct _D3DCAPS9
{
    D3DDEVTYPE  DeviceType;
    UINT        AdapterOrdinal;
    DWORD   Caps;
    DWORD   Caps2;
    DWORD   Caps3;
    DWORD   PresentationIntervals;
    DWORD   CursorCaps;
    DWORD   DevCaps;
    DWORD   PrimitiveMiscCaps;
    DWORD   RasterCaps;
    DWORD   ZCmpCaps;
    DWORD   SrcBlendCaps;
    DWORD   DestBlendCaps;
    DWORD   AlphaCmpCaps;
    DWORD   ShadeCaps;
    DWORD   TextureCaps;
    DWORD   TextureFilterCaps;          // D3DPTFILTERCAPS for IDirect3DTexture9's
    DWORD   CubeTextureFilterCaps;      // D3DPTFILTERCAPS for IDirect3DCubeTexture9's
    DWORD   VolumeTextureFilterCaps;    // D3DPTFILTERCAPS for IDirect3DVolumeTexture9's
    DWORD   TextureAddressCaps;         // D3DPTADDRESSCAPS for IDirect3DTexture9's
    DWORD   VolumeTextureAddressCaps;   // D3DPTADDRESSCAPS for IDirect3DVolumeTexture9's
    DWORD   LineCaps;                   // D3DLINECAPS
    DWORD   MaxTextureWidth, MaxTextureHeight;
    DWORD   MaxVolumeExtent;
    DWORD   MaxTextureRepeat;
    DWORD   MaxTextureAspectRatio;
    DWORD   MaxAnisotropy;
    float   MaxVertexW;
    float   GuardBandLeft;
    float   GuardBandTop;
    float   GuardBandRight;
    float   GuardBandBottom;
    float   ExtentsAdjust;
    DWORD   StencilCaps;
    DWORD   FVFCaps;
    DWORD   TextureOpCaps;
    DWORD   MaxTextureBlendStages;
    DWORD   MaxSimultaneousTextures;
    DWORD   VertexProcessingCaps;
    DWORD   MaxActiveLights;
    DWORD   MaxUserClipPlanes;
    DWORD   MaxVertexBlendMatrices;
    DWORD   MaxVertexBlendMatrixIndex;
    float   MaxPointSize;
    DWORD   MaxPrimitiveCount;          // max number of primitives per DrawPrimitive call
    DWORD   MaxVertexIndex;
    DWORD   MaxStreams;
    DWORD   MaxStreamStride;            // max stride for SetStreamSource
    DWORD   VertexShaderVersion;
    DWORD   MaxVertexShaderConst;       // number of vertex shader constant registers
    DWORD   PixelShaderVersion;
    float   PixelShader1xMaxValue;      // max value storable in registers of ps.1.x shaders
    // Here are the DX9 specific ones
    DWORD   DevCaps2;
    float   MaxNpatchTessellationLevel;
    DWORD   Reserved5;
    UINT    MasterAdapterOrdinal;       // ordinal of master adaptor for adapter group
    UINT    AdapterOrdinalInGroup;      // ordinal inside the adapter group
    UINT    NumberOfAdaptersInGroup;    // number of adapters in this adapter group (only if master)
    DWORD   DeclTypes;                  // Data types, supported in vertex declarations
    DWORD   NumSimultaneousRTs;         // Will be at least 1
    DWORD   StretchRectFilterCaps;      // Filter caps supported by StretchRect
    D3DVSHADERCAPS2_0 VS20Caps;
    D3DPSHADERCAPS2_0 PS20Caps;
    DWORD   VertexTextureFilterCaps;    // D3DPTFILTERCAPS for IDirect3DTexture9's for texture, used in vertex shaders
    DWORD   MaxVShaderInstructionsExecuted; // maximum number of vertex shader instructions that can be executed
    DWORD   MaxPShaderInstructionsExecuted; // maximum number of pixel shader instructions that can be executed
    DWORD   MaxVertexShader30InstructionSlots;
    DWORD   MaxPixelShader30InstructionSlots;
};
typedef struct _D3DCAPS9 D3DCAPS9;

#define D3DCLEAR_TARGET                    1
#define D3DCLEAR_ZBUFFER                   2
#define D3DERR_DEVICELOST                  0x88760868
#define D3DERR_DEVICENOTRESET              0x88760869
#define D3DERR_INVALIDCALL                 0x8876086C
#define D3DISSUE_BEGIN                     2
#define D3DISSUE_END                       1
#define D3DLOCK_DISCARD                    8192
#define D3DLOCK_NOOVERWRITE                4096
